### ISSUE TITLE
Shared.imageCache.get 这个方法貌似不存在

### ISSUE THREAD

**Issue by qsj** [sunxiang0918/ZhiHuDaily-Swift#1]
在引入Haneke后 发现 Shared.imageCache和Shared.dataCache没有get方法  不知道怎么编译通过的
同是java转ios 求教

**Comment by sunxiang0918** [comment]
这个方法 确实是 不存在的, 因为是我加的. Haneke的作者很久没更新了.还没有支持swift2.0,以及同步的缓存获取.  因此 我就 fork 了一个  然后改了下.

但是理论上,你直接chekout 我的项目 里面 应该是 我修改过的Haneke. 除非是 你 重新使用cocopods重新导入了framework.

如果是这样, 你可以修改 podfile里面.
pod 'HanekeSwift' , :git => 'https://git.oschina.net/xycm/HanekeSwift.git'

**Comment by qsj** [comment]
谢谢了 因为不熟悉如何配置 所以麻烦了
